# Tensor Basics

In [1]:
import tensorflow as tf

In [2]:
# initialize tensors

x_01 = tf.constant(4)
print(x_01)

x_02 = tf.constant(4.0)
print(x_02)

x_03 = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x_03)

x_04 = tf.constant([[1, 2, 3], [4, 5, 6]])  # can also use shape, dtype etc.
print(x_04)

x_05 = tf.ones((3, 3))
print(x_05)

x_06 = tf.zeros((2, 3))
print(x_06)

x_07 = tf.eye(3)
print(x_07)

x_08 = tf.random.normal((3, 3), mean=0, stddev=1)
print(x_08)

x_09 = tf.random.uniform((1, 3), minval=0, maxval=1)
print(x_09)

x_10 = tf.range(9)
print(x_10)

x_11 = tf.range(start=1, limit=10, delta=2)
print(x_11)

# converting dtypes

x_12 = tf.cast(tf.range(start=1, limit=10, delta=2), dtype=tf.float64)  # tf.int, tf.bool etc.
print(x_12)

# mathematical operations

x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

z_add = x + y  # z_add = tf.add(x, y)
z_sub = x - y  # z_sub = tf.subtract(x, y)
z_mul = x * y  # z_mul = tf.multiply(x, y)
z_div = x / y  # z_div = tf.divide(x, y)

z_exp = x ** 5

z_dot = tf.tensordot(x, y, axes=1)  # dot product
print(z_dot)

x_2 = tf.random.normal((2, 3))
y_2 = tf.random.normal((3, 4))
z_matrix_mul = x_2 @ y_2  # tf.matmul(x, y)  # matrix multiplication

# indexing

x_3 = tf.range(8)
print(x_3[:])  # same as print(x)
print(x_3[2:])
print(x_3[:5])
print(x_3[4:7])

print(x_3[::2])  # stepsize is 2
print(x_3[::-1])  # reverse order

indices = tf.constant([0, 3])  # indices to take specifically
x_ind = tf.gather(x_3, indices)  # taking specific indices
print(x_ind)

x_4 = tf.constant([[1, 2], [3, 4], [5, 6]])
print(x_4[0, :])
print(x_4[0:2, :])

# reshaping

x_5 = tf.range(9)

x_reshape = tf.reshape(x_5, (3, 3))
print(x_reshape)

x_transpose = tf.transpose(x_reshape, perm=[1, 0])
print(x_transpose)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.2929384   0.8884928   0.2542704 ]
 [-1.1739132   0.6591436   0.21706408]
 [-1.798928    1.2846293  -0.3608256 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.97719693 0.7548045  0.28464484]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([2 3 4 5 6 7], shape=(6,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([4 

# Training using Backpropagation

In [3]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)

x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0
print(x_train.shape)
print(y_train.shape)

def my_model_fully_connected():
    model = keras.Sequential(
        [
            keras.layers.InputLayer((784)),  # NOTE: not necessary, only written to print model.summary before fitting the model
            layers.Dense(512, activation='relu', name='first_layer'),
            layers.Dense(256, activation='relu', name='second_layer'),
            layers.Dense(10, activation='softmax', name='third_layer'),
            
        ]
    )
    return model

model = my_model_fully_connected()

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),  # NOTE: default is from_logits=False
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)  # verbose=0 shows nothing, verbose=1 shows progress bar
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

(60000, 28, 28)
(60000, 784)
(60000,)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
first_layer (Dense)          (None, 512)               401920    
_________________________________________________________________
second_layer (Dense)         (None, 256)               131328    
_________________________________________________________________
third_layer (Dense)          (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/5
1875/1875 - 4s - loss: 0.1850 - accuracy: 0.9438
Epoch 2/5
1875/1875 - 4s - loss: 0.0798 - accuracy: 0.9747
Epoch 3/5
1875/1875 - 4s - loss: 0.0557 - accuracy: 0.9819
Epoch 4/5
1875/1875 - 4s - loss: 0.0397 - accuracy: 0.9869
Epoch 5/5
1875/1875 - 4s - loss: 0.0340 - accuracy: 0.9891
313/313 - 0s - loss: 0.0850 - accuracy: 0.

[0.08496368676424026, 0.977400004863739]

In [5]:
print(model.layers[2].weights)
print(model.layers[2].bias.numpy())

print(model.get_layer('third_layer').weights[0])
print(model.get_layer('third_layer').weights[1])
print(model.get_layer('third_layer').bias.numpy())

[<tf.Variable 'third_layer/kernel:0' shape=(256, 10) dtype=float32, numpy=
array([[ 0.06439722,  0.20898345, -0.17276403, ..., -0.01441891,
        -0.14783616, -0.1978984 ],
       [ 0.05082258, -0.1767844 , -0.02470991, ..., -0.28280863,
        -0.22264628, -0.05214815],
       [-0.30604258,  0.3695053 , -0.25231773, ..., -0.05409916,
        -0.06300288,  0.02404477],
       ...,
       [-0.02331541,  0.0987982 , -0.10431795, ..., -0.14169882,
         0.14132002, -0.04418321],
       [ 0.05873941, -0.09746395,  0.09404477, ..., -0.26448524,
         0.02616014,  0.087489  ],
       [ 0.0884406 ,  0.04134963, -0.04357363, ..., -0.15174198,
        -0.12054659,  0.08059086]], dtype=float32)>, <tf.Variable 'third_layer/bias:0' shape=(10,) dtype=float32, numpy=
array([-0.00415965, -0.13461424, -0.00903633, -0.0716994 , -0.00954073,
       -0.01700989, -0.06083748, -0.10527664,  0.24681701,  0.05397088],
      dtype=float32)>]
[-0.00415965 -0.13461424 -0.00903633 -0.0716994  -0.0095407

# Convolutional Neural Network

In [6]:
from tensorflow.keras.datasets import cifar10

In [7]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

def my_model_cnn():
    model = keras.Sequential(
        [
            keras.layers.InputLayer((32, 32, 3)),
            layers.Conv2D(32, 3, padding='valid', activation='relu'),  # Kernel size can also be written as (3, 3)  # padding can be 'same', 'valid' etc.
            layers.MaxPooling2D(),  # by default pool_size=(2, 2)
            layers.Conv2D(64, 3, activation='relu'),
            layers.MaxPooling2D(),
            layers.Conv2D(128, 3, activation='relu'),
            layers.Flatten(),
            layers.Dense(64, activation='relu'),
            layers.Dense(10),
        ]
    )
    return model

model = my_model_cnn()

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 128)         73856     
_________________________________________________________________
flatten (Flatten)            (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 64)               

[1.014009952545166, 0.6467000246047974]

# Batch Normalization

In [8]:
def my_model_cnn_batchnorm():
    model = keras.Sequential(
        [
            keras.layers.InputLayer((32, 32, 3)),
            layers.Conv2D(32, 3, padding='valid'),
            layers.BatchNormalization(),
            layers.ReLU(),
            layers.MaxPooling2D(),
            layers.Conv2D(64, 3),
            layers.BatchNormalization(),
            layers.ReLU(),
            layers.MaxPooling2D(),
            layers.Conv2D(128, 3),
            layers.BatchNormalization(),
            layers.ReLU(),
            layers.Flatten(),
            layers.Dense(64, activation='relu'),
            layers.Dense(10),
        ]
    )
    return model

model = my_model_cnn_batchnorm()

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 30, 30, 32)        896       
_________________________________________________________________
batch_normalization (BatchNo (None, 30, 30, 32)        128       
_________________________________________________________________
re_lu (ReLU)                 (None, 30, 30, 32)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 13, 13, 64)        256       
_________________________________________________________________
re_lu_1 (ReLU)               (None, 13, 13, 64)       

[0.9281631112098694, 0.6890000104904175]

# Regularization (L2 and Dropout)

In [9]:
from tensorflow.keras import regularizers

def my_model_cnn_batchnorm_reg():
    
    model = keras.Sequential(
        [
            keras.layers.InputLayer((32, 32, 3)),
            layers.Conv2D(32, 3, padding='valid', kernel_regularizer=regularizers.l2(0.01)),
            layers.BatchNormalization(),
            layers.ReLU(),
            layers.MaxPooling2D(),
            layers.Conv2D(64, 3, kernel_regularizer=regularizers.l2(0.01)),
            layers.BatchNormalization(),
            layers.ReLU(),
            layers.MaxPooling2D(),
            layers.Conv2D(128, 3, kernel_regularizer=regularizers.l2(0.01)),
            layers.BatchNormalization(),
            layers.ReLU(),
            layers.Flatten(),
            layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
            layers.Dropout(0.5),
            layers.Dense(10),
        ]
    )
    return model

model = my_model_cnn_batchnorm_reg()

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=3e-4),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=25, verbose=2)
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 30, 30, 32)        896       
_________________________________________________________________
batch_normalization_3 (Batch (None, 30, 30, 32)        128       
_________________________________________________________________
re_lu_3 (ReLU)               (None, 30, 30, 32)        0         
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
batch_normalization_4 (Batch (None, 13, 13, 64)        256       
_________________________________________________________________
re_lu_4 (ReLU)               (None, 13, 13, 64)       

[1.032969355583191, 0.741599977016449]